### ISSUE TITLE
License

### ISSUE THREAD

**Issue by SoniEx2** [Mojang/brigadier#104]
Brigadier is currently MIT license. Would you be willing to relicense it to dual MIT/Apache-2? That would be really useful, thanks.

**Comment by Pharap** [comment]
What for? MIT is actually _more_ permissive than Apache 2.0.
Using the Apache 2.0 licence would actually force more restrictions on how forked code could be used.

**Comment by slicedlime** [comment]
The license is not changing.

**Comment by SoniEx2** [comment]
@Pharap actually it would allow picking either license. this is common with e.g. Rust.

so you can stick with MIT if you wanna stick with MIT. at most it only adds some responsibilities on the maintainers (particularly wrt patents).

**Comment by Pharap** [comment]
@SoniEx2 It would allow selecting either, but there would almost never be a reason to choose Apache 2.0 rather than MIT _because_ MIT is more permissive. The only advantage would be if you wanted to force people to document the modifications they make.

Patents would make a difference _if_ there were any in place here, but as far as I'm aware there aren't. Even if patents suddenly were an issue, it would be simple enough to fork the code from _before_ the patent-dependent were introduced, or to remove the patent-dependent code.
