### ISSUE TITLE
Sent by mistake.

### ISSUE THREAD

**Issue by hrh233** [Mojang/brigadier#113]
Sent by mistake.

**Comment by unilock** [comment]
> W269N-WFGWX-YVC9B-4J6C9-T83GX

This is a Microsoft Generic Volume License Key. It can be used to activate Windows "for free", but only when a KMS host is on the same LAN as the system being activated.
https://learn.microsoft.com/en-us/windows-server/get-started/kms-client-activation-keys#windows-11-and-windows-10-semi-annual-channel-versions

Because a KMS host in turn requires a KMS host key to set up, there's nothing inherently malicious about this key being here.
https://learn.microsoft.com/en-us/windows-server/get-started/kms-create-host#prerequisites

...But this issue should probably be deleted regardless.
