### ISSUE TITLE
Will this upgrade to Java16

### ISSUE THREAD

**Issue by xtexChooser** [Mojang/brigadier#97]
I wanted to use this library in my Android application so I can use up to Java8.

Minecraft was updated to Java16.

Will this library use Java16?

**Comment by portlek** [comment]
did you try it on Java 16? was it working or there is an issue about it?

**Comment by MiniDigger** [comment]
OPs point is trying to understand the future plans for this lib, since they are constrained to java 8 and this lib would be impossible to use for them if this lib would compile to java 16.

generally, I wouldn't be too concerned, could always fall back to an older version too, since there aren't that much changes to this lib anyways.

**Comment by xtexChooser** [comment]
> did you try it on Java 16? was it working or there is an issue about it?

No, but Minecraft was updated to Java16 and it is using this library and Minecraft1.17 was released for some time.

I think it can working prefect.
